### ISSUE TITLE
Custom property accessor is no longer supported.

### ISSUE THREAD

**Issue by JaviCerveraIngram** [mikestead/hamcrest-haxe#12]
I am trying to use MassiveUnit, which relies on hamcrest, but I am getting the following errors:

`
/home/javi/haxelib/hamcrest/2,0,1/org/hamcrest/Exception.hx:10: characters 18-26 : name: Custom property accessor is no longer supported, please use `get`
/home/javi/haxelib/hamcrest/2,0,1/org/hamcrest/Exception.hx:13: characters 21-32 : message: Custom property accessor is no longer supported, please use `get`
/home/javi/haxelib/hamcrest/2,0,1/org/hamcrest/Exception.hx:16: characters 19-28 : cause: Custom property accessor is no longer supported, please use `get`
`

It looks like Haxe 4 no longer support `get_x` syntax. It is fixed simply by replace the top of the Exception class with:

`
	public var name(get, null):String;
	function get_name():String { return name; }

	public var message(get, null):String;
	function get_message():String { return message; }

	public var cause(get, null):Dynamic;
	function get_cause():Dynamic { return cause; }
`

**Comment by mikestead** [comment]
Should be fixed under `v3.0.0`
