### ISSUE TITLE
Deprecation warning about IMap

### ISSUE THREAD

**Issue by ttencate** [mikestead/hamcrest-haxe#6]
```
.../hamcrest/2,0,1/org/hamcrest/collection/IsHashContaining.hx:36: characters 26-34 : Warning : Usage of this typedef is deprecated
```

`IsHashContaining` references the standard typedef [`IMap`](https://github.com/HaxeFoundation/haxe/blob/development/std/Map.hx#L170), which is deprecated, resulting in compiler warnings when using hamcrest. Not a huge deal, just a bit noisy.

Something along the lines of [this](https://github.com/misprintt/mockatoo/pull/57) should fix it.

**Comment by mikestead** [comment]
Fixed, released under `v3.0.0`
